language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: ./gradlew -I gradle/travis.gradle check
